// Generated by CoffeeScript 1.6.1
(function() {
  var $infoContent, autocomplete, createMarker, currentMarker, directionsRenderer, drawElevation, elevationAlongSteps, elevationService, history, infoWindow, map, setContent, startMarker;

  Array.prototype.find = function(predicate) {
    var _ref;
    return (_ref = this.filter(predicate)[0]) != null ? _ref : null;
  };

  currentMarker = null;

  startMarker = null;

  directionsRenderer = null;

  map = null;

  infoWindow = null;

  $infoContent = null;

  history = null;

  elevationService = new google.maps.ElevationService();

  elevationAlongSteps = function(steps, callback) {
    var MAGIC, deferred, deferredes, i, path, results, s, _i, _j, _len, _ref;
    MAGIC = 300;
    path = [];
    for (_i = 0, _len = steps.length; _i < _len; _i++) {
      s = steps[_i];
      path = path.concat(s.path);
    }
    deferredes = [];
    results = [];
    for (i = _j = 0, _ref = Math.floor((path.length - 1) / MAGIC); 0 <= _ref ? _j <= _ref : _j >= _ref; i = 0 <= _ref ? ++_j : --_j) {
      deferred = $.Deferred();
      deferredes.push(deferred);
      setTimeout((function(i, deferred) {
        return function() {
          return elevationService.getElevationForLocations({
            locations: path.slice(i * MAGIC, (i + 1) * MAGIC)
          }, function(result, status) {
            if (status === google.maps.ElevationStatus.OK) {
              deferred.resolve();
              return results[i] = result;
            } else {
              deferred.reject();
              return console.log(status);
            }
          });
        };
      })(i, deferred), 2000 * i);
    }
    return $.when.apply(window, deferredes).done(function() {
      var result;
      result = results.reduce(function(a, b) {
        return a.concat(b);
      });
      return callback(result);
    }).fail(function() {
      return console.log('fail');
    });
  };

  drawElevation = function(elevationResults) {
    var d, distances, elevations, i, slopes, _i, _ref;
    elevations = elevationResults.map(function(x) {
      return x.elevation;
    });
    slopes = [0];
    distances = [0];
    for (i = _i = 0, _ref = elevationResults.length - 1; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      d = google.maps.geometry.spherical.computeDistanceBetween(elevationResults[i].location, elevationResults[i + 1].location);
      slopes.push(d !== 0 ? (elevations[i + 1] - elevations[i]) / d * 100 : slopes[slopes.length - 1]);
      distances.push(distances[i] + d);
    }
    $('#container').addClass('graph');
    return $('#graph').on($.support.transition.end, function() {
      var r;
      google.maps.event.trigger(map, 'resize');
      r = Raphael('graph', innerWidth, $('#graph').innerHeight());
      r.linechart(20, 0, innerWidth - 40, $('#graph').innerHeight() / 2 - 10, distances, elevations, {
        axis: '0 1 0 1'
      });
      return r.linechart(20, $('#graph').innerHeight() / 2 - 10, innerWidth - 40, $('#graph').innerHeight() / 2 - 10, distances, slopes, {
        axis: '0 1 1 1'
      });
    });
  };

  $infoContent = $('<div>\n    <p id="description"></p>\n    <button id="start" type="button" class="btn">スタート</button>\n    <button id="goal" type="button" class="btn">ゴール</button>\n</div>');

  $infoContent.children('#start').on('click', function() {
    startMarker = currentMarker;
    return setTimeout((function() {
      return infoWindow.close();
    }), 0);
  });

  $infoContent.children('#goal').on('click', function() {
    setTimeout((function() {
      return infoWindow.close();
    }), 0);
    return new google.maps.DirectionsService().route({
      avoidHighways: true,
      avoidTolls: true,
      destination: currentMarker.getPosition(),
      origin: startMarker.getPosition(),
      provideRouteAlternatives: true,
      travelMode: google.maps.TravelMode.DRIVING
    }, function(result, status) {
      history = [];
      if (status === google.maps.DirectionsStatus.OK) {
        startMarker.setMap(null);
        currentMarker.setMap(null);
        $('#map-container').addClass('route');
        return $('#panel').one($.support.transition.end, function() {
          google.maps.event.trigger(map, 'resize');
          if (directionsRenderer != null) {
            return directionsRenderer.setDirections(result);
          } else {
            history.push({
              directionsResult: result
            });
            directionsRenderer = new google.maps.DirectionsRenderer({
              directions: result,
              draggable: true,
              map: map,
              panel: $('#directions-panel')[0]
            });
            return google.maps.event.addListener(directionsRenderer, 'directions_changed', function() {
              return history.push({
                directionsResult: this.getDirections()
              });
            });
          }
        });
      } else {
        return alert(status);
      }
    });
  });

  infoWindow = new google.maps.InfoWindow({
    content: $infoContent[0]
  });

  setContent = function(description) {
    return $infoContent.children('#description').text(description);
  };

  createMarker = function(position) {
    var marker;
    marker = new google.maps.Marker({
      animation: google.maps.Animation.DROP,
      draggable: true,
      map: map,
      position: position
    });
    return google.maps.event.addListener(marker, 'click', function() {
      currentMarker = this;
      setContent(this.getPosition().toString());
      return infoWindow.open(map, this);
    });
  };

  map = new google.maps.Map(document.getElementById('map'), {
    center: new google.maps.LatLng(34.584199, 135.835163),
    zoom: 10,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControl: false
  });

  google.maps.event.addListener(map, 'click', function(event) {
    return createMarker(event.latLng);
  });

  autocomplete = new google.maps.places.Autocomplete($('#search')[0]);

  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    var place;
    place = autocomplete.getPlace();
    if (place.geometry != null) {
      map.panTo(place.geometry.location);
      return new google.maps.Marker({
        animation: google.maps.Animation.DROP,
        draggable: true,
        map: map,
        position: place.geometry.location
      });
    }
  });

  $('#altitude').on('click', function() {
    var directions, directionsInHistory, e, index, steps, _i, _len, _ref, _ref1, _ref2;
    directions = directionsRenderer.getDirections();
    index = (_ref = directionsRenderer.getRouteIndex()) != null ? _ref : 0;
    directionsInHistory = history.find(function(e) {
      return e.directionsResult === directions;
    });
    if (((_ref1 = directionsInHistory.elevationResults) != null ? _ref1[index] : void 0) != null) {
      return drawElevation(directionsInHistory.elevationResults[index]);
    } else {
      steps = [];
      _ref2 = directions.routes[index].legs;
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        e = _ref2[_i];
        steps = steps.concat(e.steps);
      }
      return elevationAlongSteps(steps, function(result) {
        var _ref3;
        if ((_ref3 = directionsInHistory.elevationResults) == null) {
          directionsInHistory.elevationResults = [];
        }
        directionsInHistory.elevationResults[index] = result;
        return drawElevation(result);
      });
    }
  });

}).call(this);
