// Generated by CoffeeScript 1.6.1
(function() {
  var APP_NAME, CLIENT_ID, DirectionsController, Event, MAP_STATUS, Place, SCOPES, TIME_ZONE_HOST, calendars, compareEventResources, currentCalendar, currentPlace, directionsCondition, directionsController, getLocalizedString, getTimeZone, handleAuthResult, initializeDOM, initializeGoogleMaps, localTime, localize, map, mapSum, saveMapStatus, searchDirections, setLocalExpressionInto, spinner, sum, timeDifference,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CLIENT_ID = '369757625302.apps.googleusercontent.com';

  SCOPES = ['https://www.googleapis.com/auth/calendar'];

  MAP_STATUS = 'spacetime-map-status';

  TIME_ZONE_HOST = 'http://safari-park.herokuapp.com';

  APP_NAME = 'EventMaps';

  map = null;

  calendars = null;

  currentCalendar = null;

  currentPlace = null;

  directionsCondition = {
    origin: null,
    destination: null,
    time: null
  };

  directionsController = null;

  spinner = new Spinner({
    color: '#000'
  });

  sum = function(array) {
    return array.reduce(function(a, b) {
      return a + b;
    });
  };

  mapSum = function(array, fn) {
    return array.map(fn).reduce(function(a, b) {
      return a + b;
    });
  };

  getLocalizedString = function(key) {
    var _ref;
    if (typeof localizedStrings !== "undefined" && localizedStrings !== null) {
      return (_ref = localizedStrings[key]) != null ? _ref : key;
    } else {
      return key;
    }
  };

  setLocalExpressionInto = function(id, english) {
    var el;
    el = document.getElementById(id);
    if (el != null) {
      return el.lastChild.data = getLocalizedString(english);
    }
  };

  localize = function() {
    var idWordPairs, key, value, _results;
    idWordPairs = [];
    document.title = getLocalizedString(APP_NAME);
    _results = [];
    for (key in idWordPairs) {
      value = idWordPairs[key];
      _results.push(setLocalExpressionInto(key, value));
    }
    return _results;
  };

  timeDifference = function(offset) {
    var offsetHours, offsetMinutes, twoDigitsFormat;
    twoDigitsFormat = function(n) {
      if (n < 10) {
        return '0' + n;
      } else {
        return n.toString();
      }
    };
    offsetHours = Math.floor(offset / (60 * 60));
    offsetMinutes = Math.floor(offset / 60 - offsetHours * 60);
    return (offset >= 0 ? '+' : '-') + twoDigitsFormat(offsetHours) + twoDigitsFormat(offsetMinutes);
  };

  localTime = function(date, offset) {
    return new Date(date.getTime() + offset * 1000).toISOString().replace(/\..*Z/, timeDifference(offset));
  };

  getTimeZone = function(date, position, callback) {
    var location, timestamp;
    if (getTimeZone.overQueryLimit) {
      return false;
    }
    location = "" + (position.lat()) + "," + (position.lng());
    timestamp = Math.floor(date.getTime() / 1000);
    return $.getJSON("" + TIME_ZONE_HOST + "/timezone/json?location=" + location + "&timestamp=" + timestamp + "&sensor=false&callback=?", function(obj) {
      switch (obj.status) {
        case 'OK':
          return callback(obj);
        case 'OVER_QUERY_LIMIT':
          getTimeZone.overQueryLimit = true;
          setTimeout((function() {
            return getTimeZone.overQueryLimit = false;
          }), 1000);
          return alert(obj.status);
        default:
          return console.error(obj);
      }
    });
  };

  getTimeZone.overQueryLimit = false;

  compareEventResources = function(x, y) {
    var _ref, _ref1;
    return new Date((_ref = x.start.dateTime) != null ? _ref : x.start.date + 'T00:00:00Z').getTime() - new Date((_ref1 = y.start.dateTime) != null ? _ref1 : y.start.date + 'T00:00:00Z').getTime();
  };

  handleAuthResult = function(result) {
    if ((result != null) && (result.error == null)) {
      return gapi.client.load('calendar', 'v3', function() {
        $('#button-authorize').css('display', 'none');
        return $('#button-calendar').css('display', '');
      });
    } else {
      return $('#button-authorize').text("このアプリ\"" + APP_NAME + "\"にGoogleカレンダーへのアクセスを許可する").attr('disabled', null).addClass('primary');
    }
  };

  searchDirections = function(origin, destination, departureTime, callback) {
    var TRAVEL_MODES, deferred, deferreds, key, options, results, travelMode, value, _i, _len;
    TRAVEL_MODES = (function() {
      var _ref, _results;
      _ref = google.maps.TravelMode;
      _results = [];
      for (key in _ref) {
        value = _ref[key];
        _results.push(value);
      }
      return _results;
    })();
    results = [];
    deferreds = [];
    for (_i = 0, _len = TRAVEL_MODES.length; _i < _len; _i++) {
      travelMode = TRAVEL_MODES[_i];
      deferred = $.Deferred();
      deferreds.push(deferred);
      options = {
        destination: destination,
        origin: origin,
        travelMode: travelMode
      };
      if (departureTime != null) {
        options.transitOptions = {
          departureTime: departureTime
        };
      }
      searchDirections.service.route(options, (function(travelMode, deferred) {
        return function(result, status) {
          switch (status) {
            case google.maps.DirectionsStatus.OK:
              result.travelMode = travelMode;
              results.push(result);
          }
          return deferred.resolve();
        };
      })(travelMode, deferred));
    }
    return $.when.apply(window, deferreds).then(function() {
      return callback(results);
    });
  };

  searchDirections.service = new google.maps.DirectionsService();

  DirectionsController = (function() {

    DirectionsController.renderer = new google.maps.DirectionsRenderer({
      hideRouteList: false,
      map: null,
      panel: $('#directions-panel')[0]
    });

    function DirectionsController(results) {
      this.results = results;
      this.index = 0;
      this.routeIndex = 0;
    }

    DirectionsController.prototype.currentResult = function() {
      return this.results[this.index];
    };

    DirectionsController.prototype.numOfResults = function() {
      var e;
      return sum((function() {
        var _i, _len, _ref, _results;
        _ref = this.results;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          e = _ref[_i];
          _results.push(e.routes.length);
        }
        return _results;
      }).call(this));
    };

    DirectionsController.prototype.next = function() {
      this.routeIndex += 1;
      if (this.routeIndex >= this.results[this.index].routes.length) {
        this.index += 1;
        if (this.index >= this.results.length) {
          this.index = 0;
        }
        return this.routeIdex = 0;
      }
    };

    DirectionsController.prototype.prev = function() {
      this.routeIndex -= 1;
      if (this.routeIndex < 0) {
        this.index -= 1;
        if (this.index < 0) {
          this.index = this.results.length - 1;
        }
        return this.routeIdex = this.results[this.index].routes.length - 1;
      }
    };

    DirectionsController.prototype.show = function() {
      var result;
      result = this.currentResult();
      map.setMapTypeId((function() {
        switch (result.travelMode) {
          case google.maps.TravelMode.BICYCLING:
          case google.maps.TravelMode.WALKING:
            return google.maps.MapTypeId.TERRAIN;
          default:
            return google.maps.MapTypeId.ROADMAP;
        }
      })());
      DirectionsController.renderer.setDirections(result);
      DirectionsController.renderer.setRouteIndex(this.routeIndex);
      DirectionsController.renderer.setMap(map);
      return $('#button-route-info').removeClass('hide');
    };

    DirectionsController.prototype.clear = function() {
      DirectionsController.renderer.setMap(null);
      map.setMapTypeId(google.maps.MapTypeId.ROADMAP);
      $('#button-route-info').addClass('hide');
      return this.results = null;
    };

    return DirectionsController;

  })();

  saveMapStatus = function() {
    var pos;
    pos = map.getCenter();
    return localStorage[MAP_STATUS] = JSON.stringify({
      lat: pos.lat(),
      lng: pos.lng(),
      zoom: map.getZoom()
    });
  };

  Place = (function(_super) {

    __extends(Place, _super);

    function Place(options, event, candidateAddress) {
      var _this = this;
      this.event = event;
      this.candidateAddress = candidateAddress != null ? candidateAddress : null;
      Place.__super__.constructor.call(this, options);
      google.maps.event.addListener(this, 'click', function() {
        if ((directionsCondition.origin != null) && (directionsCondition.destination == null)) {
          return _this.showDirections();
        } else {
          return _this.showInfo();
        }
      });
    }

    Place.prototype.getDateTime = function(startOrEnd) {
      var dateTime, time, _ref;
      dateTime = (_ref = this.event.resource[startOrEnd].dateTime) != null ? _ref : this.event.resource[startOrEnd].date + 'T00:00:00Z';
      if (this["" + startOrEnd + "TimeZone"] != null) {
        time = localTime(new Date(dateTime), this["" + startOrEnd + "TimeZone"].dstOffset + this["" + startOrEnd + "TimeZone"].rawOffset);
        return {
          date: time.replace(/T.*/, ''),
          time: time.replace(/.*T|[Z+-].*/g, '')
        };
      } else {
        return {
          date: dateTime.replace(/T.*/, ''),
          time: dateTime.replace(/.*T|[Z+-].*/g, '')
        };
      }
    };

    Place.prototype.showInfo = function() {
      this.event.setModal(this);
      Event.$modal.modal('show');
      directionsCondition = {
        origin: null,
        destination: null,
        time: null
      };
      if (directionsController != null) {
        directionsController.clear();
        return directionsController = null;
      }
    };

    Place.prototype.showDirections = function() {
      var time;
      directionsCondition.destination = this;
      time = (function() {
        switch (directionsCondition.time) {
          case 'now':
            return new Date();
          case 'origin':
            return directionsCondition.origin.event.getDate('end');
          case 'destination':
            return this.event.getDate('start');
          default:
            return null;
        }
      }).call(this);
      return searchDirections(directionsCondition.origin.getPosition(), this.getPosition(), time, function(results) {
        /*
        for result, i in results
            for route in result.routes
                route.distance = mapSum result.routes[0].legs, (e) -> e.distance.value
                route.duration = mapSum result.routes[0].legs, (e) -> e.duration.value
        */
        results.sort(function(x, y) {
          return x.routes[0].duration - y.routes[0].duration;
        });
        directionsController = new DirectionsController(results);
        return directionsController.show();
      });
    };

    return Place;

  })(google.maps.Marker);

  Event = (function() {

    Event.$modal = $('#modal-info');

    Event.events = [];

    Event.placeNumber = 0;

    Event.geocodeCount = 0;

    Event.shadow = {
      url: 'http://www.google.com/mapfiles/shadow50.png',
      anchor: new google.maps.Point(10, 34)
    };

    Event.clearAll = function() {
      var e, _i, _len, _ref;
      _ref = Event.events;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        e = _ref[_i];
        e.clearMarkers();
      }
      Event.events = [];
      return Event.placeNumber = 0;
    };

    function Event(calendarId, resource, centering, byClick) {
      var _base, _base1, _base2, _base3, _base4, _ref, _ref1, _ref2, _ref3, _ref4;
      this.calendarId = calendarId;
      this.resource = resource;
      if (centering == null) {
        centering = false;
      }
      if (byClick == null) {
        byClick = false;
      }
      if ((_ref = (_base = this.resource).summary) == null) {
        _base.summary = '新しい予定';
      }
      if ((_ref1 = (_base1 = this.resource).location) == null) {
        _base1.location = '';
      }
      if ((_ref2 = (_base2 = this.resource).description) == null) {
        _base2.description = '';
      }
      if ((_ref3 = (_base3 = this.resource).start) == null) {
        _base3.start = {
          dateTime: new Date().toISOString()
        };
      }
      if ((_ref4 = (_base4 = this.resource).end) == null) {
        _base4.end = {
          dateTime: new Date().toISOString()
        };
      }
      this.dirty = false;
      this.candidates = null;
      if ((this.getPosition() != null) || ((this.resource.location != null) && this.resource.location !== '')) {
        this.placeNumber = Event.placeNumber;
        Event.placeNumber += 1;
        this.tryToSetPlace(centering, byClick);
      }
      Event.events.push(this);
    }

    Event.prototype.clearMarkers = function() {
      var e, _i, _len, _ref;
      if (this.place != null) {
        this.place.setMap(null);
      }
      this.place = null;
      if (this.candidates != null) {
        _ref = this.candidates;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          e = _ref[_i];
          e.setMap(null);
        }
      }
      return this.candidates = null;
    };

    Event.prototype.getDate = function(startOrEnd) {
      var _ref;
      return new Date((_ref = this.resource[startOrEnd].dateTime) != null ? _ref : this.resource[startOrEnd].date + (startOrEnd === 'start' ? 'T00:00:00Z' : 'T23:59:59Z'));
    };

    Event.prototype.getPosition = function() {
      var geolocation, _ref, _ref1;
      if (((_ref = this.resource.extendedProperties) != null ? (_ref1 = _ref["private"]) != null ? _ref1.geolocation : void 0 : void 0) != null) {
        geolocation = JSON.parse(this.resource.extendedProperties["private"].geolocation);
        if ((geolocation.location == null) || geolocation.location === this.resource.location) {
          return new google.maps.LatLng(geolocation.lat, geolocation.lng);
        } else {
          return null;
        }
      } else {
        return null;
      }
    };

    Event.prototype.getAddress = function() {
      var geolocation, _ref, _ref1;
      if (((_ref = this.resource.extendedProperties) != null ? (_ref1 = _ref["private"]) != null ? _ref1.geolocation : void 0 : void 0) != null) {
        geolocation = JSON.parse(this.resource.extendedProperties["private"].geolocation);
        return geolocation.address;
      } else {
        return null;
      }
    };

    Event.prototype.setGeolocation = function(lat, lng, address) {
      var _base, _base1, _ref, _ref1;
      if ((_ref = (_base = this.resource).extendedProperties) == null) {
        _base.extendedProperties = {};
      }
      if ((_ref1 = (_base1 = this.resource.extendedProperties)["private"]) == null) {
        _base1["private"] = {};
      }
      if (!((this.resource.location != null) && this.resource.location !== '')) {
        this.resource.location = address;
      }
      return this.resource.extendedProperties["private"].geolocation = JSON.stringify({
        lat: lat,
        lng: lng,
        address: address,
        location: this.resource.location
      });
    };

    Event.prototype.update = function() {
      if (this.calendarId != null) {
        return gapi.client.calendar.events.update({
          calendarId: this.calendarId,
          eventId: this.resource.id,
          resource: this.resource
        }).execute(function(resp) {
          if (resp.error != null) {
            return console.error('gapi.client.calendar.events.update', resp);
          }
        });
      } else {
        return $('#modal-calendar').modal('show');
      }
    };

    Event.prototype.insert = function() {
      var _this = this;
      if (this.calendarId != null) {
        return gapi.client.calendar.events.insert({
          calendarId: this.calendarId,
          resource: this.resource
        }).execute(function(resp) {
          if (resp.error != null) {
            return console.error('gapi.client.calendar.events.update', resp);
          } else {
            return _this.resource = resp.result;
          }
        });
      } else {
        return $('#modal-calendar').modal('show');
      }
    };

    Event.prototype.geocode = function(callback) {
      var latLng, options,
        _this = this;
      if (Event.geocodeCount > 10) {
        console.log('too many geocoding requests');
        return false;
      }
      latLng = this.getPosition();
      if (latLng != null) {
        options = {
          location: latLng
        };
      } else if (this.resource.location !== '') {
        options = {
          address: this.resource.location
        };
      } else {
        console.error('no hints for geocode');
        return;
      }
      new google.maps.Geocoder().geocode(options, function(results, status) {
        switch (status) {
          case google.maps.GeocoderStatus.OK:
            if (results.length === 1) {
              _this.setGeolocation(results[0].geometry.location.lat(), results[0].geometry.location.lng(), results[0].formatted_address);
              _this.update();
            }
            return callback(results);
          case google.maps.GeocoderStatus.ZERO_RESULTS:
            return setTimeout((function() {
              return alert("" + _this.resource.location + "が見つかりません");
            }), 0);
          default:
            return console.error(status);
        }
      });
      return Event.geocodeCount += 1;
    };

    Event.prototype.getIcon = function(candidate) {
      var alphabet, remainder;
      if (candidate == null) {
        candidate = false;
      }
      remainder = function(m, n) {
        return m - Math.floor(m / n) * n;
      };
      alphabet = String.fromCharCode(Math.min('A'.charCodeAt(0) + remainder(this.placeNumber, 26), 'Z'.charCodeAt(0)));
      if (candidate) {
        return {
          url: "http://maps.google.com/mapfiles/marker_grey" + alphabet + ".png"
        };
      } else {
        switch (Math.floor(this.placeNumber / 26)) {
          case 0:
            return {
              url: "http://maps.google.com/mapfiles/marker" + alphabet + ".png"
            };
          case 1:
            return {
              url: "http://maps.google.com/mapfiles/marker_orange" + alphabet + ".png"
            };
          case 2:
            return {
              url: "http://maps.google.com/mapfiles/marker_yellow" + alphabet + ".png"
            };
          case 3:
            return {
              url: "http://maps.google.com/mapfiles/marker_green" + alphabet + ".png"
            };
          default:
            return {
              url: "http://maps.google.com/mapfiles/marker_blue" + alphabet + ".png"
            };
        }
      }
    };

    Event.prototype.setPlace = function(byClick) {
      var latLng;
      if (byClick == null) {
        byClick = false;
      }
      latLng = this.getPosition();
      if (!latLng) {
        this.place = null;
        return null;
      }
      this.place = new Place({
        map: map,
        position: latLng,
        icon: this.getIcon(),
        shadow: Event.shadow,
        title: this.resource.location,
        animation: byClick ? google.maps.Animation.DROP : null
      }, this);
      return this.place.addListener('animation_changed', function() {
        if (byClick) {
          return this.showInfo();
        }
      });
    };

    Event.prototype.tryToSetPlace = function(centering, byClick, callback) {
      var _this = this;
      if (callback == null) {
        callback = function() {};
      }
      this.setPlace(byClick);
      if ((this.place != null) && centering) {
        map.setCenter(this.place.getPosition());
        currentPlace = this.place;
      }
      if ((this.place != null) && (this.getAddress() != null)) {
        callback();
        return;
      }
      return this.geocode(function(results) {
        var e, _i, _len;
        if (byClick) {
          _this.setGeolocation(results[0].geometry.location.lat(), results[0].geometry.location.lng(), results[0].formatted_address);
        } else if (results.length === 1) {
          _this.setGeolocation(results[0].geometry.location.lat(), results[0].geometry.location.lng(), results[0].formatted_address);
          _this.setPlace();
          if ((_this.place != null) && centering) {
            map.setCenter(_this.place.getPosition());
            currentPlace = _this.place;
          }
        } else {
          _this.candidates = [];
          for (_i = 0, _len = results.length; _i < _len; _i++) {
            e = results[_i];
            _this.candidates.push(new Place({
              map: map,
              position: e.geometry.location,
              icon: _this.getIcon(true),
              shadow: Event.shadow,
              title: _this.resource.location + '?'
            }, _this, e.formatted_address));
          }
          if (centering) {
            map.setCenter(_this.candidates[0].getPosition());
            currentPlace = _this.candidates[0];
          }
        }
        return callback();
      });
    };

    Event.prototype.setModal = function(place) {
      var e, endDeferred, i, setTime, startDeferred;
      Event.$modal.data('place', place);
      currentPlace = place;
      Event.$modal.find('input[name="summary"]').val(this.resource.summary);
      Event.$modal.find('input[name="location"]').val(this.resource.location);
      if ((this.resource.start.date != null) && (this.resource.end.date != null)) {
        $('#form-event input[name="all-day"]')[0].checked = true;
        $('#form-event input[name="all-day"]').trigger('change');
        Event.$modal.find('input[name="start-date"]').val(this.resource.start.date);
        Event.$modal.find('input[name="end-date"]').val(this.resource.end.date);
      } else if ((this.resource.start.dateTime != null) && (this.resource.end.dateTime != null)) {
        setTime = function(startOrEnd) {
          var dateTime;
          dateTime = place.getDateTime(startOrEnd);
          Event.$modal.find("input[name=\"" + startOrEnd + "-date\"]").val(dateTime.date);
          return Event.$modal.find("input[name=\"" + startOrEnd + "-time\"]").val(dateTime.time);
        };
        $('#form-event input[name="all-day"]')[0].checked = false;
        $('#form-event input[name="all-day"]').trigger('change');
        startDeferred = $.Deferred();
        endDeferred = $.Deferred();
        $.when(startDeferred, endDeferred).then(function() {
          return spinner.stop();
        });
        spinner.spin(document.body);
        if (place.startTimeZone != null) {
          startDeferred.resolve();
          setTime('start');
        } else {
          getTimeZone(new Date(this.resource.start.dateTime), place.getPosition(), function(obj) {
            startDeferred.resolve();
            place.startTimeZone = obj;
            return setTime('start');
          });
        }
        if (place.endTimeZone != null) {
          endDeferred.resolve();
          setTime('end');
        } else {
          getTimeZone(new Date(this.resource.end.dateTime), place.getPosition(), function(obj) {
            endDeferred.resolve();
            place.endTimeZone = obj;
            return setTime('end');
          });
        }
      } else {
        console.error('inconsistent start and end');
      }
      if (this.candidates != null) {
        $('#candidate').css('display', 'block');
        $('#candidate select[name="candidate"]').html(((function() {
          var _i, _len, _ref, _results;
          _ref = this.candidates;
          _results = [];
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            e = _ref[i];
            _results.push("<option value=\"" + i + "\" " + (e === place ? 'selected' : '') + ">" + e.candidateAddress + "</option>");
          }
          return _results;
        }).call(this)).join(''));
      } else {
        $('#candidate').css('display', 'none');
      }
      return Event.$modal.find('input[name="description"]').val(this.resource.description);
    };

    return Event;

  })();

  initializeDOM = function() {
    var $calendarList;
    localize();
    $('#container').css('display', '');
    new FastClick(document.body);
    $('#button-authorize').on('click', function() {
      return gapi.auth.authorize({
        'client_id': CLIENT_ID,
        'scope': SCOPES,
        'immediate': false
      }, handleAuthResult);
    });
    $calendarList = $('#calendar-list');
    $('#modal-calendar').on('show', function(event) {
      var req;
      req = gapi.client.calendar.calendarList.list();
      return req.execute(function(resp) {
        var e;
        if (resp.error != null) {
          return console.error(resp);
        } else {
          calendars = resp.items;
          return $calendarList.html('<option value="new">新規作成</option>' + ((function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = calendars.length; _i < _len; _i++) {
              e = calendars[_i];
              _results.push("<option value=\"" + e.id + "\">" + e.summary + "</option>");
            }
            return _results;
          })()).join(''));
        }
      });
    });
    $('#button-show').on('click', function() {
      var e, id, name, options, req, _i, _j, _len, _len1, _ref;
      if (Event.events.length > 0 && (Event.events[0].calendarId != null)) {
        Event.clearAll();
      }
      currentPlace = null;
      id = $calendarList.children('option:selected').attr('value');
      if (id === 'new') {
        if (name = prompt('新しいカレンダーに名前をつけてください')) {
          req = gapi.client.calendar.calendars.insert({
            resource: {
              summary: name
            }
          });
          return req.execute(function(resp) {
            var e, _i, _len, _ref, _results;
            if (resp.error != null) {
              return alert('カレンダーが作成できませんでした');
            } else {
              currentCalendar = resp.result;
              calendars.push(currentCalendar);
              _ref = Event.events;
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                e = _ref[_i];
                _results.push(e.calendarId = currentCalendar.id);
              }
              return _results;
            }
          });
        }
      } else {
        for (_i = 0, _len = calendars.length; _i < _len; _i++) {
          e = calendars[_i];
          if (e.id === id) {
            currentCalendar = e;
            break;
          }
        }
        _ref = Event.events;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          e = _ref[_j];
          e.calendarId = currentCalendar.id;
        }
        options = {
          calendarId: id
        };
        if ($('#form-calendar [name="start-date"]')[0].value !== '') {
          options.timeMin = $('#form-calendar [name="start-date"]')[0].value + 'T00:00:00Z';
        }
        if ($('#form-calendar [name="end-date"]')[0].value !== '') {
          options.timeMax = $('#form-calendar [name="end-date"]')[0].value + 'T00:00:00Z';
        }
        req = gapi.client.calendar.events.list(options);
        return req.execute(function(resp) {
          var event, i, _k, _len2, _ref1, _ref2, _results;
          if (resp.error != null) {
            return console.error(resp);
          } else if (((_ref1 = resp.items) != null ? _ref1.length : void 0) > 0) {
            resp.items.sort(compareEventResources);
            Event.geocodeCount = 0;
            _ref2 = resp.items;
            _results = [];
            for (i = _k = 0, _len2 = _ref2.length; _k < _len2; i = ++_k) {
              e = _ref2[i];
              _results.push(event = new Event(id, e));
            }
            return _results;
          }
        });
      }
    });
    $('#button-confirm').on('click', function() {
      var candidate, candidateIndex, position;
      candidateIndex = parseInt($('#form-event select[name="candidate"]').val());
      candidate = Event.$modal.data('place').event.candidates[candidateIndex];
      position = candidate.getPosition();
      Event.$modal.data('place').event.setGeolocation(position.lat(), position.lng(), candidate.candidateAddress);
      Event.$modal.data('place').event.dirty = true;
      Event.$modal.data('place').event.clearMarkers();
      Event.$modal.data('place').event.setPlace();
      return $('#candidate').css('display', 'none');
    });
    $('#button-update').on('click', function() {
      var anEvent, endDateTime, startDateTime, timeZone;
      anEvent = Event.$modal.data('place').event;
      if (anEvent.resource.id != null) {
        if (anEvent.resource.summary !== $('#form-event input[name="summary"]').val()) {
          anEvent.dirty = true;
          anEvent.resource.summary = $('#form-event input[name="summary"]').val();
        }
        if (anEvent.resource.location !== $('#form-event input[name="location"]').val()) {
          anEvent.dirty = true;
          anEvent.resource.location = $('#form-event input[name="location"]').val();
          delete anEvent.resource.extendedProperties["private"].geolocation;
        }
        if ($('#form-event input[name="all-day"]')[0].checked) {
          if (anEvent.resource.start.date !== $('#form-event input[name="start-date"]').val().replace(/-/g, '/')) {
            anEvent.dirty = true;
            delete anEvent.resource.start.dateTime;
            anEvent.resource.start.date = $('#form-event input[name="start-date"]').val().replace(/-/g, '/');
          }
          if (anEvent.resource.end.date !== $('#form-event input[name="end-date"]').val().replace(/-/g, '/')) {
            anEvent.dirty = true;
            delete anEvent.resource.end.dateTime;
            anEvent.resource.end.date = $('#form-event input[name="end-date"]').val().replace(/-/g, '/');
          }
        } else {
          timeZone = Event.$modal.data('place').startTimeZone;
          startDateTime = new Date($('#form-event input[name="start-date"]').val().replace(/-/g, '/') + ' ' + $('#form-event input[name="start-time"]').val() + timeDifference(timeZone.dstOffset + timeZone.rawOffset));
          if (new Date(anEvent.resource.start.dateTime).getTime() !== startDateTime.getTime()) {
            anEvent.dirty = true;
            delete anEvent.resource.start.date;
            anEvent.resource.start.dateTime = startDateTime.toISOString();
            anEvent.resource.start.timeZone = timeZone.timeZoneId;
          }
          timeZone = Event.$modal.data('place').endTimeZone;
          endDateTime = new Date($('#form-event input[name="end-date"]').val().replace(/-/g, '/') + ' ' + $('#form-event input[name="end-time"]').val() + timeDifference(timeZone.dstOffset + timeZone.rawOffset));
          if (new Date(anEvent.resource.end.dateTime).getTime() !== endDateTime.getTime()) {
            anEvent.dirty = true;
            delete anEvent.resource.end.date;
            anEvent.resource.end.dateTime = endDateTime.toISOString();
            anEvent.resource.end.timeZone = timeZone.timeZoneId;
          }
        }
        if (anEvent.resource.description !== $('#form-event input[name="description"]').val()) {
          anEvent.dirty = true;
          anEvent.resource.description = $('#form-event input[name="description"]').val();
        }
        if (anEvent.dirty) {
          return anEvent.update();
        }
      } else {
        return anEvent.insert();
      }
    });
    $('#modal-info').on('hide', function() {
      return spinner.stop();
    });
    $('#form-event input[name="all-day"]').on('change', function() {
      $('#form-event input[name="start-time"]').css('display', this.checked ? 'none' : '');
      return $('#form-event input[name="end-time"]').css('display', this.checked ? 'none' : '');
    });
    $('#button-delete').on('click', function() {
      var anEvent, req;
      anEvent = Event.$modal.data('place').event;
      if ((anEvent.calendarId != null) && (anEvent.resource.id != null)) {
        req = gapi.client.calendar.events["delete"]({
          calendarId: anEvent.calendarId,
          eventId: anEvent.resource.id
        });
        req.execute(function(resp) {
          if (resp.error != null) {
            return alert('予定が削除できませんでした');
          }
        });
      }
      Event.events.splice(Event.events.indexOf(anEvent, 1));
      anEvent.clearMarkers();
      return Event.$modal.data('place', null);
    });
    $('#button-prev, #button-next').on('click', function() {
      var candidateIndex, eventIndex, sorted, _ref, _ref1, _ref2, _ref3;
      if (directionsController != null) {
        if (directionsController.numOfResults() === 1) {
          alert('道順は１つしか見つかりませんでした');
          return;
        }
        if (this.id === 'buttion-prev') {
          directionsController.prev();
        } else {
          directionsController.next();
        }
        return directionsController.show();
      } else {
        if (Event.events.length === 0) {
          return;
        }
        sorted = Event.events.filter(function(e) {
          return (e.place != null) || (e.candidates != null);
        }).sort(function(x, y) {
          return compareEventResources(x.resource, y.resource);
        });
        if (currentPlace != null) {
          eventIndex = sorted.indexOf(currentPlace.event);
          if (Event.events[eventIndex].candidates != null) {
            candidateIndex = Event.events[eventIndex].candidates.indexOf(currentPlace);
            if (this.id === 'button-prev') {
              candidateIndex -= 1;
              if (candidateIndex < 0) {
                candidateIndex = null;
              }
            } else {
              candidateIndex += 1;
              if (candidateIndex >= Event.events[eventIndex].candidates.length) {
                candidateIndex = null;
              }
            }
          }
          if (candidateIndex != null) {
            currentPlace = Event.events[eventIndex].candidates[candidateIndex];
          } else {
            if (this.id === 'button-prev') {
              eventIndex -= 1;
              if (eventIndex < 0) {
                eventIndex = sorted.length - 1;
              }
              candidateIndex = ((_ref = Event.events[eventIndex].candidates) != null ? _ref.length : void 0) - 1;
            } else {
              eventIndex += 1;
              if (eventIndex >= sorted.length) {
                eventIndex = 0;
              }
              candidateIndex = 0;
            }
            currentPlace = (_ref1 = sorted[eventIndex].place) != null ? _ref1 : sorted[eventIndex].candidates[candidateIndex];
          }
        } else if (this.id === 'button-next') {
          currentPlace = (_ref2 = sorted[0].place) != null ? _ref2 : sorted[0].candidates[0];
        } else {
          currentPlace = (_ref3 = sorted[sorted.length - 1].place) != null ? _ref3 : sorted[sorted.length - 1].candidates[sorted[sorted.length - 1].candidates.length - 1];
        }
        return map.panTo(currentPlace.getPosition());
      }
    });
    $('#button-direction').on('click', function(event) {
      directionsCondition.origin = Event.$modal.data('place');
      return $('#modal-directions').modal('show');
    });
    $('#button-direction-search').on('click', function(event) {
      return directionsCondition.time = $('#form-directions input:checked').val();
    });
    $('#candidate select[name="candidate"]').on('change', function(event) {
      Event.$modal.data('place', Event.$modal.data('place').event.candidates[parseInt(this.value)]);
      return map.panTo(Event.$modal.data('place').getPosition());
    });
    $('#button-search').on('click', function(event) {
      var _ref, _ref1;
      Event.$modal.data('place').event.resource.location = $('#form-event input[name="location"]').val();
      Event.$modal.data('place').event.clearMarkers();
      if ((_ref = Event.$modal.data('place').event.resource.extendedProperties) != null) {
        if ((_ref1 = _ref["private"]) != null) {
          _ref1.geolocation = null;
        }
      }
      return Event.$modal.data('place').event.tryToSetPlace(true, false, function() {
        return currentPlace.event.setModal(currentPlace);
      });
    });
    $('#button-route-info').on('click', function() {
      if ($('#directions-panel').hasClass('hide')) {
        return $('#directions-panel').removeClass('hide');
      } else {
        return $('#directions-panel').addClass('hide');
      }
    });
    return $('#directions-panel').on('click', function() {
      return $('#directions-panel').addClass('hide');
    });
  };

  initializeGoogleMaps = function(callback) {
    var listener, mapOptions, mapStatus;
    if (callback == null) {
      callback = function() {};
    }
    mapOptions = {
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      disableDefaultUI: /iPad|iPhone/.test(navigator.userAgent),
      mapTypeControl: false,
      zoomControlOptions: {
        position: google.maps.ControlPosition.LEFT_CENTER
      },
      panControlOptions: {
        position: google.maps.ControlPosition.LEFT_CENTER
      }
    };
    if (localStorage[MAP_STATUS] != null) {
      mapStatus = JSON.parse(localStorage[MAP_STATUS]);
      mapOptions.center = new google.maps.LatLng(mapStatus.lat, mapStatus.lng);
      mapOptions.zoom = mapStatus.zoom;
    } else {
      mapOptions.center = new google.maps.LatLng(35.660389, 139.729225);
      mapOptions.zoom = 14;
    }
    map = new google.maps.Map(document.getElementById('map'), mapOptions);
    map.setTilt(45);
    listener = map.addListener('tilesloaded', function() {
      google.maps.event.removeListener(listener);
      return callback();
    });
    return map.addListener('click', function(event) {
      return new Event(currentCalendar != null ? currentCalendar.id : void 0, {
        extendedProperties: {
          "private": {
            geolocation: JSON.stringify({
              lat: event.latLng.lat(),
              lng: event.latLng.lng()
            })
          }
        }
      }, false, true);
    });
  };

  window.app = {
    initialize: function(mapsCallback) {
      initializeGoogleMaps(mapsCallback);
      return initializeDOM();
    },
    saveMapStatus: saveMapStatus
  };

  window.handleClientLoad = function() {
    return setTimeout((function() {
      return gapi.auth.authorize({
        'client_id': CLIENT_ID,
        'scope': SCOPES,
        'immediate': true
      }, handleAuthResult);
    }), 1);
  };

}).call(this);
