// Generated by CoffeeScript 1.3.3
(function() {
  var $addressField, $destinationField, $gps, $map, $originField, $pinList, Bookmark, DEFAULT_ICON_SIZE, MSMARKER_SHADOW, MapFSM, MapState, MobileInfoWindow, PURPLE_DOT_IMAGE, RED_DOT_IMAGE, WatchPosition, bookmarkContext, bookmarks, currentBookmark, directionsRenderer, droppedBookmark, generateBookmarkList, generateHistoryList, geocoder, getArriveAtMessage, getDepartAtMessage, getLocalizedString, getMapType, getPanoramaHandler, getTravelMode, history, infoWindow, initializeDOM, initializeGoogleMaps, isHold, localize, map, mapFSM, mapSum, maxHistory, meterToString, method, name, naviMarker, navigate, pinRowHeight, pulsatingMarker, saveMapStatus, saveOtherStatus, searchAddress, searchBookmark, searchDirections, secondToString, setInfoPage, setLocalExpressionInto, sum, traceHandler, updateField, updateMessage, _ref, _ref1, _ref2, _ref3,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PURPLE_DOT_IMAGE = 'http://maps.google.co.jp/mapfiles/ms/icons/purple-dot.png';

  RED_DOT_IMAGE = 'http://maps.google.co.jp/mapfiles/ms/icons/red-dot.png';

  MSMARKER_SHADOW = 'http://maps.google.co.jp/mapfiles/ms/icons/msmarker.shadow.png';

  DEFAULT_ICON_SIZE = 32;

  map = null;

  geocoder = null;

  directionsRenderer = null;

  pulsatingMarker = null;

  naviMarker = null;

  infoWindow = null;

  droppedBookmark = null;

  searchBookmark = null;

  currentBookmark = null;

  $map = null;

  $gps = null;

  $addressField = null;

  $originField = null;

  $destinationField = null;

  $pinList = null;

  pinRowHeight = null;

  mapFSM = null;

  bookmarkContext = null;

  bookmarks = [];

  history = [];

  maxHistory = 20;

  isHold = true;

  MobileInfoWindow = (function(_super) {

    __extends(MobileInfoWindow, _super);

    function MobileInfoWindow(options) {
      this.setOptions(options);
    }

    MobileInfoWindow.prototype.close = function() {
      return this.setMap(null);
    };

    MobileInfoWindow.prototype.getContent = function() {
      return this.content;
    };

    MobileInfoWindow.prototype.getPosition = function() {
      return this.position;
    };

    MobileInfoWindow.prototype.getZIndex = function() {
      return this.zIndex;
    };

    MobileInfoWindow.prototype.open = function(map, anchor) {
      var icon, markerAnchor, markerSize, _ref;
      this.anchor = anchor;
      if (anchor != null) {
        this.setPosition(this.anchor.getPosition());
        icon = this.anchor.getIcon();
        if (icon != null) {
          markerSize = icon.size;
          markerAnchor = (_ref = icon.anchor) != null ? _ref : new google.maps.Point(Math.floor(markerSize.width / 2), markerSize.height);
        } else {
          markerSize = new google.maps.Size(DEFAULT_ICON_SIZE, DEFAULT_ICON_SIZE);
          markerAnchor = new google.maps.Point(DEFAULT_ICON_SIZE / 2, DEFAULT_ICON_SIZE);
        }
        this.pixelOffset = new google.maps.Size(Math.floor(markerSize.width / 2) - markerAnchor.x, -markerAnchor.y, 'px', 'px');
      }
      return this.setMap(map);
    };

    MobileInfoWindow.prototype.setContent = function(content) {
      this.content = content;
      if (this.element == null) {
        this.element = document.createElement('div');
        if (this.maxWidth) {
          this.element.style['max-width'] = this.maxWidth + 'px';
        }
        this.element.className = 'info-window';
      }
      if (typeof this.content === 'string') {
        this.element.innerHTML = this.content;
      } else {
        this.element.appendChild(this.content);
      }
      return google.maps.event.trigger(this, 'content_changed');
    };

    MobileInfoWindow.prototype.setOptions = function(options) {
      var _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      this.maxWidth = (_ref = options.maxWidth) != null ? _ref : null;
      this.setContent((_ref1 = options.content) != null ? _ref1 : '');
      this.disableAutoPan = (_ref2 = options.disableAutoPan) != null ? _ref2 : null;
      this.pixelOffset = (_ref3 = options.pixelOffset) != null ? _ref3 : google.maps.Size(0, 0, 'px', 'px');
      this.setPosition((_ref4 = options.position) != null ? _ref4 : null);
      return this.setZIndex((_ref5 = options.zIndex) != null ? _ref5 : 0);
    };

    MobileInfoWindow.prototype.setPosition = function(position) {
      this.position = position;
      return google.maps.event.trigger(this, 'position_changed');
    };

    MobileInfoWindow.prototype.setZIndex = function(zIndex) {
      this.zIndex = zIndex;
      this.element.style['z-index'] = this.zIndex.toString();
      return google.maps.event.trigger(this, 'zindex_changed');
    };

    MobileInfoWindow.prototype.onAdd = function() {
      this.getPanes().floatPane.appendChild(this.element);
      this.listeners = [];
      return google.maps.event.trigger(this, 'domready');
    };

    MobileInfoWindow.prototype.draw = function() {
      var xy;
      xy = this.getProjection().fromLatLngToDivPixel(this.getPosition());
      this.element.style.left = xy.x + this.pixelOffset.width - this.element.offsetWidth / 2 + 'px';
      return this.element.style.top = xy.y + this.pixelOffset.height - this.element.offsetHeight + 'px';
    };

    MobileInfoWindow.prototype.onRemove = function() {
      this.listeners.forEach(function(e) {
        return google.maps.event.removeListener(e);
      });
      this.element.parentNode.removeChild(this.element);
      return this.element = null;
    };

    return MobileInfoWindow;

  })(google.maps.OverlayView);

  WatchPosition = (function() {

    function WatchPosition() {}

    WatchPosition.prototype.start = function(dummy) {
      if (dummy != null) {
        this.id = navigator.geolocation.watchPosition.apply(navigator.geolocation, Array.prototype.slice.call(arguments));
      } else {
        this.id = navigator.geolocation.watchPosition(traceHandler, function(error) {
          return console.log(error.message, {
            enableHighAccuracy: true,
            timeout: 30000
          });
        });
      }
      return this;
    };

    WatchPosition.prototype.stop = function() {
      if (!this.id) {
        navigator.geolocation.clearWatch(this.id);
      }
      this.id = null;
      return this;
    };

    return WatchPosition;

  })();

  MapState = (function() {

    function MapState(name) {
      this.name = name;
    }

    MapState.NORMAL = new MapState('normal');

    MapState.TRACE_POSITION = new MapState('trace_position');

    MapState.TRACE_HEADING = new MapState('trace_heading');

    MapState.prototype.update = function() {
      return this;
    };

    MapState.prototype.gpsClicked = function() {
      return this;
    };

    MapState.prototype.bookmarkClicked = function() {
      return this;
    };

    return MapState;

  })();

  MapState.NORMAL.update = function() {
    $gps.removeClass('btn-light');
    return this;
  };

  MapState.NORMAL.gpsClicked = function() {
    return MapState.TRACE_POSITION;
  };

  MapState.TRACE_POSITION.update = function() {
    if (pulsatingMarker.getVisible()) {
      map.setCenter(pulsatingMarker.getPosition());
    }
    $gps.addClass('btn-light');
    return this;
  };

  MapState.TRACE_POSITION.gpsClicked = function() {
    return MapState.NORMAL;
  };

  MapState.TRACE_HEADING.update = function() {
    return this;
  };

  MapState.TRACE_HEADING.gpsClicked = function() {
    return MapState.NORMAL;
  };

  MapState.TRACE_HEADING.bookmarkClicked = function() {
    return MapState.TRACE_POSITION;
  };

  MapFSM = (function() {

    function MapFSM(state) {
      this.state = state;
    }

    MapFSM.prototype.is = function(state) {
      return this.state === state;
    };

    MapFSM.prototype.setState = function(state) {
      if (this.state === state) {
        return;
      }
      this.state = state;
      return this.state.update();
    };

    return MapFSM;

  })();

  _ref = MapState.prototype;
  for (name in _ref) {
    method = _ref[name];
    if (typeof method === 'function') {
      MapFSM.prototype[name] = (function(name) {
        return function() {
          return this.setState(this.state[name]());
        };
      })(name);
    }
  }

  Bookmark = (function() {

    function Bookmark(marker, address) {
      var _this = this;
      this.marker = marker;
      this.address = address;
      google.maps.event.addListener(this.marker, 'click', function(event) {
        currentBookmark = _this;
        return _this.showInfoWindow();
      });
    }

    Bookmark.prototype.setInfoWindow = function() {
      var makeInfoMessage;
      makeInfoMessage = function(title, message) {
        return "<table id=\"info-window\"><tr>\n    <td><button id=\"street-view\" class=\"btn btn-mini\"><i class=\"icon-user icon-white\"></i></button></td>\n    <td style=\"white-space: nowrap;\"><div style=\"max-width:160px;overflow:hidden;\">" + title + "<br><span id=\"dropped-message\" style=\"font-size:10px\">" + message + "</span></div></td>\n    <td><button id=\"button-info\" class=\"btn btn-mini btn-light\"><i class=\"icon-chevron-right icon-white\"></i></button></td>\n</tr></table>";
      };
      return infoWindow.setContent(makeInfoMessage(this.marker.getTitle(), this.address));
    };

    Bookmark.prototype.showInfoWindow = function() {
      this.setInfoWindow();
      return infoWindow.open(map, this.marker);
    };

    Bookmark.prototype.toObject = function() {
      var pos;
      pos = this.marker.getPosition();
      return {
        lat: pos.lat(),
        lng: pos.lng(),
        title: this.marker.getTitle(),
        address: this.address
      };
    };

    return Bookmark;

  })();

  window.getRouteIndexMessage = (_ref1 = window.getRouteIndexMessage) != null ? _ref1 : function(index, total) {
    var ordinal;
    ordinal = function(n) {
      switch (n % 10) {
        case 1:
          return '1st';
        case 2:
          return '2nd';
        case 3:
          return '3rd';
        default:
          return n + 'th';
      }
    };
    return "" + (ordinal(index + 1)) + " of " + total + " Suggested Routes";
  };

  getDepartAtMessage = (_ref2 = window.getDepartAtMessage) != null ? _ref2 : function(time) {
    return 'Departs at ' + time;
  };

  getArriveAtMessage = (_ref3 = window.getArriveAtMessage) != null ? _ref3 : function(time) {
    return 'Arrives at ' + time;
  };

  getLocalizedString = function(key) {
    var _ref4;
    if (typeof localizedStrings !== "undefined" && localizedStrings !== null) {
      return (_ref4 = localizedStrings[key]) != null ? _ref4 : key;
    } else {
      return key;
    }
  };

  setLocalExpressionInto = function(id, english) {
    return document.getElementById(id).lastChild.data = getLocalizedString(english);
  };

  localize = function() {
    var idWordPairs, key, value, _results;
    idWordPairs = {
      'replace-pin': 'Replace Pin',
      'print': 'Print',
      'traffic': 'Show Traffic',
      'roadmap': 'Standard',
      'satellite': 'Satellite',
      'panel': 'List',
      'hybrid': 'Hybrid',
      'clear': 'Clear',
      'map-title': 'Search',
      'done': 'Done',
      'edit': 'Edit',
      'versatile': 'Start',
      'origin-label': 'Start: ',
      'destination-label': 'End: ',
      'edit2': 'Edit',
      'search': 'Search',
      'route': 'Directions',
      'bookmark-message': 'Choose a bookmark to view on the map',
      'bookmark-edit': 'Edit',
      'bookmark-done': 'Done',
      'bookmark-title': 'Bookmarks',
      'bookmark': 'Bookmarks',
      'history': 'Recents',
      'contact': 'Contacts',
      'button-map': 'Map',
      'info-title': 'Info',
      'address-label': 'address',
      'to-here': 'Directions To Here',
      'from-here': 'Directions From Here',
      'delete-pin': 'Remove Pin',
      'add-into-contact': 'Add to Contacts',
      'send-place': 'Share Location',
      'add-bookmark': 'Add to Bookmarks',
      'add-bookmark-message': 'Type a name for the bookmark',
      'cancel-add-bookmark': 'Cancel',
      'add-bookmark-title': 'Add Bookmark',
      'save-bookmark': 'Save',
      'edit3': 'Edit',
      'directions-title': 'Directions'
    };
    document.title = getLocalizedString('Maps');
    document.getElementById('search-input').placeholder = getLocalizedString('Search or Address');
    _results = [];
    for (key in idWordPairs) {
      value = idWordPairs[key];
      _results.push(setLocalExpressionInto(key, value));
    }
    return _results;
  };

  saveMapStatus = function() {
    var pos;
    pos = map.getCenter();
    return localStorage['maps-map-status'] = JSON.stringify({
      lat: pos.lat(),
      lng: pos.lng(),
      zoom: map.getZoom()
    });
  };

  saveOtherStatus = function() {
    history.splice(maxHistory);
    return localStorage['maps-other-status'] = JSON.stringify({
      origin: $originField.val(),
      destination: $destinationField.val(),
      bookmarks: bookmarks.map(function(e) {
        return e.toObject();
      }),
      history: history
    });
  };

  sum = function(array) {
    return array.reduce(function(a, b) {
      return a + b;
    });
  };

  mapSum = function(array, fn) {
    return array.map(fn).reduce(function(a, b) {
      return a + b;
    });
  };

  secondToString = function(sec) {
    var day, hour, min, result;
    result = '';
    min = Math.floor(sec / 60);
    sec -= min * 60;
    hour = Math.floor(min / 60);
    min -= hour * 60;
    day = Math.floor(hour / 24);
    hour -= day * 24;
    result += day === 1 ? day + getLocalizedString('day') : day > 1 ? day + getLocalizedString('days') : '';
    if (day < 10) {
      result += hour === 1 ? hour + getLocalizedString('hour') : hour > 1 ? hour + getLocalizedString('hours') : '';
    }
    if (day === 0 && hour < 10) {
      result += min === 1 ? min + getLocalizedString('minute') : min > 1 ? min + getLocalizedString('minutes') : '';
    }
    return result;
  };

  meterToString = function(meter) {
    if (meter < 1000) {
      return meter + 'm';
    } else {
      return parseFloat((meter / 1000).toPrecision(2)) + 'km';
    }
  };

  getTravelMode = function() {
    return google.maps.TravelMode[$('#travel-mode').children('.btn-primary').attr('id').toUpperCase()];
  };

  getMapType = function() {
    return google.maps.MapTypeId[$('#map-type').children('.btn-primary').attr('id').toUpperCase()];
  };

  searchAddress = function(fromHistory) {
    var address;
    address = $addressField.val();
    if (!((address != null) && address !== '')) {
      return;
    }
    infoWindow.close();
    searchBookmark.marker.setVisible(false);
    if (!fromHistory) {
      history.unshift({
        type: 'search',
        address: address
      });
    }
    return geocoder.geocode({
      address: address
    }, function(result, status) {
      if (status === google.maps.GeocoderStatus.OK) {
        mapFSM.setState(MapState.NORMAL);
        map.setCenter(result[0].geometry.location);
        searchBookmark.address = result[0].formatted_address;
        searchBookmark.marker.setPosition(result[0].geometry.location);
        searchBookmark.marker.setTitle(address);
        searchBookmark.marker.setVisible(true);
        searchBookmark.marker.setAnimation(google.maps.Animation.DROP);
        return currentBookmark = searchBookmark;
      } else {
        return alert(status);
      }
    });
  };

  updateMessage = function() {
    var $message, distance, duration, index, message, result, route, summary;
    index = directionsRenderer.getRouteIndex();
    result = directionsRenderer.getDirections();
    route = result.routes[index];
    $message = $('#message');
    message = '';
    if (result.routes.length > 1) {
      message += getRouteIndexMessage(index, result.routes.length) + '<br>';
    }
    if (getTravelMode() === google.maps.TravelMode.TRANSIT) {
      summary = getDepartAtMessage(route.legs[0].departure_time.text);
      summary += '<br>';
      summary += getArriveAtMessage(route.legs[route.legs.length - 1].arrival_time.text);
    } else {
      distance = mapSum(result.routes[index].legs, function(e) {
        return e.distance.value;
      });
      duration = mapSum(result.routes[index].legs, function(e) {
        return e.duration.value;
      });
      summary = "" + (secondToString(duration)) + " - " + (meterToString(distance)) + " - " + result.routes[index].summary;
      if (summary.length > innerWidth / parseInt($message.css('font-size'))) {
        summary = "" + result.routes[index].summary + "<br>" + (secondToString(duration)) + " - " + (meterToString(distance));
      }
    }
    message += summary;
    return $message.html(message);
  };

  searchDirections = function(fromHistory) {
    var destination, origin, travelMode;
    if (fromHistory == null) {
      fromHistory = false;
    }
    origin = $originField.val();
    destination = $destinationField.val();
    if (!((origin != null) && origin !== '' && (destination != null) && destination !== '')) {
      return;
    }
    if (!fromHistory) {
      history.unshift({
        type: 'route',
        origin: origin,
        destination: destination
      });
    }
    travelMode = getTravelMode();
    return searchDirections.service.route({
      destination: destination,
      origin: origin,
      provideRouteAlternatives: getTravelMode() !== google.maps.TravelMode.WALKING,
      travelMode: travelMode
    }, function(result, status) {
      var mode;
      switch (status) {
        case google.maps.DirectionsStatus.OK:
          directionsRenderer.setMap(map);
          directionsRenderer.setDirections(result);
          return updateMessage();
        case google.maps.DirectionsStatus.ZERO_RESULTS:
          directionsRenderer.setMap(null);
          mode = $('#travel-mode').children('.btn-primary').attr('id');
          mode = mode[0].toUpperCase() + mode.substr(1);
          $('#message').html(getLocalizedString(mode + ' directions could not be found between these locations'));
          return Alert(getLocalizedString('Directions Not Available\nDirections could not be found between these locations.'));
        default:
          directionsRenderer.setMap(null);
          return console.log(status);
      }
    });
  };

  searchDirections.service = new google.maps.DirectionsService();

  navigate = function(str) {
    var lengths, route, step, steps, _ref4;
    route = (_ref4 = directionsRenderer.getDirections()) != null ? _ref4.routes[directionsRenderer.getRouteIndex()] : void 0;
    if (route == null) {
      return;
    }
    switch (str) {
      case 'start':
        navigate.leg = 0;
        navigate.step = 0;
        $('#navi-header2').css('display', 'block');
        naviMarker.setVisible(true);
        break;
      case 'next':
        if (navigate.step < route.legs[navigate.leg].steps.length - 1) {
          navigate.step += 1;
        } else if (navigate.leg < route.legs.length - 1) {
          navigate.leg += 1;
          navigate.step = 0;
        }
        break;
      case 'previous':
        if (navigate.step > 0) {
          navigate.step -= 1;
        } else if (navigate.leg > 0) {
          navigate.leg -= 1;
          navigate.step = route.legs[navigate.leg].steps.legth - 1;
        }
    }
    map.setZoom(15);
    step = route.legs[navigate.leg].steps[navigate.step];
    naviMarker.setPosition(step.start_location);
    map.setCenter(step.start_location);
    lengths = route.legs.map(function(e) {
      return e.steps.length;
    });
    steps = navigate.step + (navigate.leg === 0 ? 0 : sum(lengths.slice(0, navigate.leg)));
    $('#numbering').text((steps + 1) + '/' + mapSum(route.legs, function(e) {
      return e.steps.length;
    }));
    return $('#message').html(step.instructions);
  };

  navigate.leg = null;

  navigate.step = null;

  updateField = function($field, str) {
    return $field.val(str).siblings('.btn-bookmark').css('display', str === '' ? 'block' : 'none');
  };

  setInfoPage = function(bookmark, dropped) {
    var position, title, _ref4, _ref5;
    $('#info-marker img:first-child').attr('src', (_ref4 = (_ref5 = bookmark.marker.getIcon()) != null ? _ref5.url : void 0) != null ? _ref4 : 'http://maps.google.co.jp/mapfiles/ms/icons/red-dot.png');
    title = bookmark.marker.getTitle();
    position = bookmark.marker.getPosition();
    $('#info-name').text(title);
    $('#bookmark-name input[name="bookmark-name"]').val(dropped ? bookmark.address : title);
    $('#info-address').text(bookmark.address);
    return $('#send-place').attr('href', "mailto:?subject=" + title + "&body=<a href=\"https://maps.google.co.jp/maps?q=" + (position.lat()) + "," + (position.lng()) + "\">" + title + "</a>");
  };

  generateBookmarkList = function() {
    var e, i, list, _i, _len;
    list = "<tr><td data-object-name=\"pulsatingMarker\">" + (getLocalizedString('Current Location')) + "</td></tr>";
    if (droppedBookmark.marker.getVisible()) {
      list += "<tr><td data-object-name=\"droppedBookmark\">" + (getLocalizedString('Dropped Pin')) + "</td></tr>";
    }
    for (i = _i = 0, _len = bookmarks.length; _i < _len; i = ++_i) {
      e = bookmarks[i];
      list += "<tr><td data-object-name=\"bookmarks[" + i + "]\">" + (e.marker.getTitle()) + "</td></tr>";
    }
    list += Array(Math.max(1, Math.floor(innerHeight / pinRowHeight) - bookmarks.length)).join('<tr><td></td></tr>');
    return $pinList.html(list);
  };

  generateHistoryList = function() {
    var e, i, list, print, _i, _len;
    print = function(e) {
      switch (e.type) {
        case 'search':
          return getLocalizedString('Search: ') + e.address;
        case 'route':
          return getLocalizedString('Start: ') + e.origin + '<br>' + getLocalizedString('End: ') + e.destination;
      }
    };
    list = '';
    for (i = _i = 0, _len = history.length; _i < _len; i = ++_i) {
      e = history[i];
      list += "<tr><td data-object-name=\"history[" + i + "]\">" + (print(e)) + "</td></tr>";
    }
    list += Array(Math.max(1, Math.floor(innerHeight / pinRowHeight) - history.length)).join('<tr><td></td></tr>');
    return $pinList.html(list);
  };

  getPanoramaHandler = function(data, status) {
    var sv, _ref4;
    switch (status) {
      case google.maps.StreetViewStatus.OK:
        sv = map.getStreetView();
        sv.setPosition(data.location.latLng);
        sv.setPov({
          heading: (_ref4 = map.getHeading()) != null ? _ref4 : 0,
          pitch: 0,
          zoom: 1
        });
        return sv.setVisible(true);
      case google.maps.StreetViewStatus.ZERO_RESULTS:
        return alert(getLocalizedString('There are no street views near here.'));
      default:
        return alert(getLocaliedString('Sorry, an error occurred.'));
    }
  };

  traceHandler = function(position) {
    var latLng, transform;
    latLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
    pulsatingMarker.setVisible(true);
    pulsatingMarker.setPosition(latLng);
    if (!mapFSM.is(MapState.NORMAL)) {
      map.setCenter(latLng);
    }
    if (mapFSM.is(MapState.TRACE_HEADING && (position.coords.heading != null))) {
      transform = $map.css('-webkit-transform');
      if (/rotate(-?[\d.]+deg)/.test(transform)) {
        transform = transform.replace(/rotate(-?[\d.]+deg)/, "rotate(" + (-position.coords.heading) + "deg)");
      } else {
        transform = transform + (" rotate(" + (-position.coords.heading) + "deg)");
      }
      return $map.css('-webkit-transform', transform);
    }
  };

  initializeGoogleMaps = function() {
    var mapOptions, mapStatus;
    mapOptions = {
      mapTypeId: getMapType(),
      disableDefaultUI: true
    };
    if (localStorage['maps-map-status'] != null) {
      mapStatus = JSON.parse(localStorage['maps-map-status']);
      mapOptions.center = new google.maps.LatLng(mapStatus.lat, mapStatus.lng);
      mapOptions.zoom = mapStatus.zoom;
    } else {
      mapOptions.center = new google.maps.LatLng(35.660389, 139.729225);
      mapOptions.zoom = 14;
    }
    map = new google.maps.Map(document.getElementById("map"), mapOptions);
    mapFSM = new MapFSM(MapState.NORMAL);
    geocoder = new google.maps.Geocoder();
    infoWindow = new MobileInfoWindow({
      maxWidth: Math.floor(innerWidth * 0.9)
    });
    directionsRenderer = new google.maps.DirectionsRenderer({
      hideRouteList: false,
      infoWindow: infoWindow,
      map: map,
      panel: $('#directions-panel')[0]
    });
    google.maps.event.addListener(directionsRenderer, 'directions_changed', function() {
      navigate.leg = null;
      navigate.step = null;
      $('#navi-header2').css('display', 'none');
      return naviMarker.setVisible(false);
    });
    pulsatingMarker = new google.maps.Marker({
      flat: true,
      icon: new google.maps.MarkerImage('img/bluedot.png', null, null, new google.maps.Point(8, 8), new google.maps.Size(17, 17)),
      map: map,
      optimized: false,
      position: mapOptions.center,
      title: 'I might be here',
      visible: false
    });
    droppedBookmark = new Bookmark(new google.maps.Marker({
      animation: google.maps.Animation.DROP,
      map: map,
      icon: new google.maps.MarkerImage(PURPLE_DOT_IMAGE),
      shadow: new google.maps.MarkerImage(MSMARKER_SHADOW, null, null, new google.maps.Point(DEFAULT_ICON_SIZE / 2, DEFAULT_ICON_SIZE)),
      position: mapOptions.center,
      title: getLocalizedString('Dropped Pin'),
      visible: false
    }), '');
    searchBookmark = new Bookmark(new google.maps.Marker({
      animation: google.maps.Animation.DROP,
      map: map,
      position: mapOptions.center,
      visible: false
    }), '');
    google.maps.event.addListener(infoWindow, 'domready', function() {
      $('#street-view').on('click', function(event) {
        return new google.maps.StreetViewService().getPanoramaByLocation(currentBookmark.marker.getPosition(), 49, getPanoramaHandler);
      });
      return $('#button-info').on('click', function(event) {
        setInfoPage(currentBookmark, currentBookmark === droppedBookmark);
        return $('#container').css('right', '100%');
      });
    });
    naviMarker = new google.maps.Marker({
      flat: true,
      icon: new google.maps.MarkerImage('img/bluedot.png', null, null, new google.maps.Point(8, 8), new google.maps.Size(17, 17)),
      map: map,
      optimized: false,
      visible: false
    });
    google.maps.event.addListener(map, 'click', function(event) {
      var $infoWindow, position, xy, _ref4, _ref5;
      if (!isHold) {
        infoWindow.close();
        return;
      }
      $infoWindow = $('.info-window');
      if ($infoWindow.length > 0) {
        xy = infoWindow.getProjection().fromLatLngToDivPixel(event.latLng);
        position = $infoWindow.position();
        if (((position.left <= (_ref4 = xy.x) && _ref4 <= position.left + $infoWindow.width())) && ((position.top <= (_ref5 = xy.y) && _ref5 <= position.top + $infoWindow.height()))) {
          return;
        }
      }
      infoWindow.close();
      droppedBookmark.address = '';
      droppedBookmark.marker.setVisible(true);
      droppedBookmark.marker.setPosition(event.latLng);
      droppedBookmark.marker.setAnimation(google.maps.Animation.DROP);
      currentBookmark = droppedBookmark;
      return geocoder.geocode({
        latLng: event.latLng
      }, function(result, status) {
        droppedBookmark.address = status === google.maps.GeocoderStatus.OK ? result[0].formatted_address.replace(/日本, /, '') : getLocalizedString('No information');
        return droppedBookmark.setInfoWindow();
      });
    });
    google.maps.event.addListener(droppedBookmark.marker, 'animation_changed', function() {
      if (!(this.getAnimation() != null)) {
        return droppedBookmark.showInfoWindow();
      }
    });
    google.maps.event.addListener(searchBookmark.marker, 'animation_changed', function() {
      if (!(this.getAnimation() != null)) {
        return searchBookmark.showInfoWindow();
      }
    });
    google.maps.event.addListener(map, 'dragstart', function() {
      return mapFSM.setState(MapState.NORMAL);
    });
    google.maps.event.addListener(map, 'center_changed', saveMapStatus);
    return google.maps.event.addListener(map, 'zoom_changed', saveMapStatus);
  };

  initializeDOM = function() {
    var $bookmarkPage, $edit, $mapType, $naviHeader, $option, $route, $routeSearchFrame, $search, $traffic, $travelMode, $versatile, backToMap, e, layout, openRouteForm, otherStatus, trafficLayer, _i, _len, _ref4, _ref5, _ref6;
    $map = $('#map');
    $gps = $('#gps');
    $addressField = $('#address input[name="address"]');
    $originField = $('#origin input[name="origin"]');
    $destinationField = $('#destination input[name="destination"]');
    $pinList = $('#pin-list');
    pinRowHeight = $('#pin-list tr').height();
    document.addEventListener('touchmove', function(event) {
      return event.preventDefault();
    });
    $('#pin-list-frame, #info, #directions-panel').on('touchmove', function(event) {
      return event.stopPropagation();
    });
    if (localStorage['maps-other-status'] != null) {
      otherStatus = JSON.parse(localStorage['maps-other-status']);
      if ((otherStatus.origin != null) && otherStatus.origin !== '') {
        updateField($originField, otherStatus.origin);
      }
      if ((otherStatus.destination != null) && otherStatus.destination !== '') {
        updateField($destinationField, otherStatus.destination);
      }
      _ref5 = (_ref4 = otherStatus.bookmarks) != null ? _ref4 : [];
      for (_i = 0, _len = _ref5.length; _i < _len; _i++) {
        e = _ref5[_i];
        bookmarks.push(new Bookmark(new google.maps.Marker({
          map: map,
          position: new google.maps.LatLng(e.lat, e.lng),
          title: e.title
        }), e.address));
      }
      history = (_ref6 = otherStatus.history) != null ? _ref6 : [];
    }
    localize();
    layout = function() {
      var height, visibleSearchHeaderHeight;
      $('#option-page').css('bottom', $('#footer').outerHeight(true));
      visibleSearchHeaderHeight = $('#search-header').outerHeight(true) + parseInt($('#search-header').css('top'));
      $map.css('top', visibleSearchHeaderHeight + 'px');
      height = innerHeight - visibleSearchHeaderHeight - $('#footer').outerHeight(true);
      $map.height(height);
      $('#directions-panel').height(height);
      $('#pin-list-frame').css('height', innerHeight - mapSum($('#bookmark-page > div:not(#pin-list-frame)').toArray(), function(e) {
        return $(e).outerHeight(true);
      }) + 'px');
      if (!(/iPhone/.test(navigator.userAgent) && /Safari/.test(navigator.userAgent))) {
        return document.body.scrollLeft = 0;
      }
    };
    layout();
    window.addEventListener('resize', layout);
    $map.on('touchstart', function() {
      isHold = false;
      return setTimeout((function() {
        return isHold = true;
      }), 500);
    });
    $('.search-query').on('keyup', function() {
      var $this;
      $this = $(this);
      if ($this.val() === '') {
        return $this.siblings('.btn-bookmark').css('display', 'block');
      } else {
        return $this.siblings('.btn-bookmark').css('display', 'none');
      }
    });
    $('#clear, .btn-reset').on('mousedown', function(event) {
      return event.preventDefault();
    });
    $('.btn-reset').on('click', function() {
      return $(this).siblings('.btn-bookmark').css('display', 'block');
    });
    $('#clear').on('click', function() {
      return $('#address .btn-bookmark').css('display', 'block');
    });
    $gps.on('click', function() {
      return mapFSM.gpsClicked();
    });
    $addressField.on('focus', function() {
      return $('#search-header').css('top', '0');
    });
    $addressField.on('blur', function() {
      return $('#search-header').css('top', '');
    });
    $('#address').on('submit', function() {
      searchAddress(false);
      $addressField.blur();
      return false;
    });
    $addressField.on('keyup', function() {
      return setLocalExpressionInto('done', $(this).val() === '' ? 'Done' : 'Cancel');
    });
    $('#clear, #address .btn-reset').on('click', function() {
      setLocalExpressionInto('done', 'Done');
      searchBookmark.marker.setVisible(false);
      if (currentBookmark === searchBookmark) {
        return infoWindow.setVisible(false);
      }
    });
    $naviHeader = $('#navi-header1');
    $search = $('#search');
    $search.on('click', function() {
      directionsRenderer.setMap(null);
      naviMarker.setVisible(false);
      $route.removeClass('btn-primary');
      $search.addClass('btn-primary');
      return $naviHeader.css('display', 'none');
    });
    $route = $('#route');
    $route.on('click', function() {
      $search.removeClass('btn-primary');
      $route.addClass('btn-primary');
      $naviHeader.css('display', 'block');
      return directionsRenderer.setMap(map);
    });
    $edit = $('#edit');
    $versatile = $('#versatile');
    $routeSearchFrame = $('#route-search-frame');
    openRouteForm = function() {
      setLocalExpressionInto('edit', 'Cancel');
      setLocalExpressionInto('versatile', 'Route');
      $('#navi-header2').css('display', 'none');
      $routeSearchFrame.css('top', '0px');
      return $destinationField.focus();
    };
    $edit.on('click', function() {
      if ($edit.text().replace(/^\s*|\s*$/, '') === getLocalizedString('Edit')) {
        return openRouteForm();
      } else {
        setLocalExpressionInto('edit', 'Edit');
        setLocalExpressionInto('versatile', 'Start');
        if ((navigate.leg != null) && (navigate.step != null)) {
          $('#navi-header2').css('display', 'block');
        }
        return $routeSearchFrame.css('top', '');
      }
    });
    $('#edit2').on('click', function() {
      return $edit.trigger('click');
    });
    $('#switch').on('click', function() {
      var tmp;
      tmp = $destinationField.val();
      updateField($destinationField, $originField.val());
      updateField($originField, tmp);
      return saveOtherStatus();
    });
    $('#origin, #destination').on('submit', function() {
      return false;
    });
    $originField.on('change', saveOtherStatus);
    $destinationField.on('change', saveOtherStatus);
    $travelMode = $('#travel-mode');
    $travelMode.children().on('click', function() {
      var $this;
      $this = $(this);
      if ($this.hasClass('btn-primary')) {
        return;
      }
      $travelMode.children().removeClass('btn-primary');
      return $this.addClass('btn-primary');
    });
    $versatile.on('click', function() {
      switch ($versatile.text().replace(/^\s*|\s*$/, '')) {
        case getLocalizedString('Route'):
          setLocalExpressionInto('edit', 'Edit');
          setLocalExpressionInto('versatile', 'Start');
          $routeSearchFrame.css('top', '');
          return searchDirections(false);
        case getLocalizedString('Start'):
          return navigate('start');
      }
    });
    $('#cursor-left').on('click', function() {
      return navigate('previous');
    });
    $('#cursor-right').on('click', function() {
      return navigate('next');
    });
    backToMap = function() {
      $map.css('top', '');
      $('#directions-panel').css('top', '');
      return $option.removeClass('btn-primary');
    };
    $option = $('#option');
    $option.on('click', function() {
      $('#option-page').css('display', 'block');
      if ($option.hasClass('btn-primary')) {
        return backToMap();
      } else {
        $map.css('top', $('#search-header .toolbar').outerHeight() - $('#option-page').outerHeight(true) + 'px');
        $('#directions-panel').css('top', $('#directions-header').outerHeight() - $('#option-page').outerHeight(true) + 'px');
        return $option.addClass('btn-primary');
      }
    });
    $mapType = $('#map-type');
    $mapType.children(':not(#panel)').on('click', function() {
      var $this;
      $this = $(this);
      if ($this.hasClass('btn-primary')) {
        return;
      }
      $mapType.children().removeClass('btn-primary');
      $this.addClass('btn-primary');
      map.setMapTypeId(getMapType());
      $('#directions-window').css('display', 'none');
      updateMessage();
      return backToMap();
    });
    $('#panel').on('click', function() {
      var $this;
      $this = $(this);
      if ($this.hasClass('btn-primary')) {
        return;
      }
      $mapType.children().removeClass('btn-primary');
      $this.addClass('btn-primary');
      $('#directions-window').css('display', 'block');
      return backToMap();
    });
    $traffic = $('#traffic');
    trafficLayer = new google.maps.TrafficLayer();
    $traffic.on('click', function() {
      if ($traffic.text() === getLocalizedString('Show Traffic')) {
        trafficLayer.setMap(map);
        setLocalExpressionInto('traffic', 'Hide Traffic');
      } else {
        trafficLayer.setMap(null);
        setLocalExpressionInto('traffic', 'Show Traffic');
      }
      return backToMap();
    });
    $('#replace-pin').on('click', function() {
      droppedBookmark.marker.setPosition(map.getCenter());
      droppedBookmark.marker.setVisible(true);
      return backToMap();
    });
    $('#print').on('click', function() {
      setTimeout(window.print, 0);
      return backToMap();
    });
    $('#button-map').on('click', function() {
      return $('#container').css('right', '');
    });
    $bookmarkPage = $('#bookmark-page');
    $('.btn-bookmark').on('click', function() {
      var ancestor;
      mapFSM.bookmarkClicked();
      ancestor = $(this).parent();
      while (ancestor.size() > 0 && ancestor[0].nodeName !== 'FORM') {
        ancestor = ancestor.parent();
      }
      bookmarkContext = ancestor.attr('id');
      generateBookmarkList();
      return $bookmarkPage.css('bottom', '0');
    });
    $('#bookmark-done').on('click', function() {
      return $bookmarkPage.css('bottom', '-100%');
    });
    $(document).on('click', '#pin-list td', function() {
      var bookmarkOrMarker, item, latLng;
      name = $(this).data('object-name');
      if (!((name != null) && name !== '')) {
        return;
      }
      if (/history/.test(name)) {
        item = eval(name);
        switch (item.type) {
          case 'search':
            updateField($addressField, item.address);
            $search.trigger('click');
            searchAddress(true);
            break;
          case 'route':
            updateField($originField, item.origin);
            updateField($destinationField, item.destination);
            $route.trigger('click');
            searchDirections(true);
        }
      } else {
        bookmarkOrMarker = eval(name);
        switch (bookmarkContext) {
          case 'address':
            map.getStreetView().setVisible(false);
            if (name === 'pulsatingMarker') {
              mapFSM.setState(MapState.TRACE_POSITION);
            } else {
              mapFSM.setState(MapState.NORMAL);
              if (bookmarkOrMarker !== droppedBookmark) {
                updateField($addressField, bookmarkOrMarker.address);
              }
              map.setCenter(bookmarkOrMarker.marker.getPosition());
              currentBookmark = bookmarkOrMarker;
              bookmarkOrMarker.showInfoWindow();
            }
            break;
          case 'origin':
            updateField($originField, name === 'pulsatingMarker' ? (latLng = bookmarkOrMarker.getPosition(), "" + (latLng.lat()) + ", " + (latLng.lng())) : bookmarkOrMarker.address);
            break;
          case 'destination':
            updateField($destinationField, name === 'pulsatingMarker' ? (latLng = bookmarkOrMarker.getPosition(), "" + (latLng.lat()) + ", " + (latLng.lng())) : bookmarkOrMarker.address);
        }
      }
      return $bookmarkPage.css('bottom', '-100%');
    });
    $('#add-bookmark').on('click', function() {
      return $('#add-bookmark-page').css('top', '0');
    });
    $('#cancel-add-bookmark').on('click', function() {
      return $('#add-bookmark-page').css('top', '');
    });
    $('#delete-pin').on('click', function() {
      var index;
      if (currentBookmark === droppedBookmark) {
        droppedBookmark.marker.setVisible(false);
      } else {
        index = bookmarks.indexOf(currentBookmark);
        bookmarks.splice(index, 1);
        currentBookmark.marker.setMap(null);
      }
      infoWindow.close();
      return $('#container').css('right', '');
    });
    $('#save-bookmark').on('click', function() {
      var bookmark;
      bookmark = new Bookmark(new google.maps.Marker({
        map: map,
        position: currentBookmark.marker.getPosition(),
        title: $('#bookmark-name input[name="bookmark-name"]').val()
      }), $('#info-address').text());
      bookmarks.push(bookmark);
      bookmark.showInfoWindow();
      saveOtherStatus();
      $('#add-bookmark-page').css('top', '');
      return $('#container').css('right', '');
    });
    $('#nav-bookmark button').on('click', function() {
      var $this;
      $this = $(this);
      $('#nav-bookmark button').removeClass('btn-primary');
      $this.addClass('btn-primary');
      switch ($this.attr('id')) {
        case 'bookmark':
          setLocalExpressionInto('bookmark-message', 'Choose a bookmark to view on the map');
          setLocalExpressionInto('bookmark-edit', 'Edit');
          $('#bookmark-edit').addClass('disabled');
          return generateBookmarkList();
        case 'history':
          setLocalExpressionInto('bookmark-message', 'Choose a recent search');
          setLocalExpressionInto('bookmark-edit', 'Clear');
          $('#bookmark-edit').removeClass('disabled');
          return generateHistoryList();
      }
    });
    $('#bookmark-edit').on('click', function() {
      switch ($(this).text()) {
        case getLocalizedString('Clear'):
          if (confirm(getLocalizedString('Clear All Recents'))) {
            history = [];
            return generateHistoryList();
          }
      }
    });
    $('#to-here').on('click', function() {
      updateField($destinationField, currentBookmark.address);
      $route.trigger('click');
      $('#container').css('right', '');
      return openRouteForm();
    });
    return $('#from-here').on('click', function() {
      updateField($originField, currentBookmark.address);
      $route.trigger('click');
      $('#container').css('right', '');
      return openRouteForm();
    });
  };

  window.app = {
    WatchPosition: WatchPosition,
    initializeDOM: initializeDOM,
    initializeGoogleMaps: initializeGoogleMaps,
    saveMapStatus: saveMapStatus,
    saveOtherStatus: saveOtherStatus
  };

}).call(this);
