// Generated by CoffeeScript 1.6.1
(function() {
  var $option, $version, BLINK_INTERVAL, STARTUP_TIME, VERSION, fullScreen, timerId, type, types, _i, _len;

  VERSION = '(C) 2013 ICHIKAWA, Yuji (New 3 Rs)<br>Maps ver. 2.0.0';

  BLINK_INTERVAL = 500;

  STARTUP_TIME = 3000;

  timerId = null;

  $option = $('#option');

  $version = $('#version');

  fullScreen = function() {
    var $body, $dummy;
    $body = $(document.body);
    $dummy = $("<div id=\"dummy\" style=\"position: absolute; width: 100%; height: " + screen.availHeight + "px; top: 0px\"></div>");
    $body.append($dummy);
    window.addEventListener('orientationchange', (function() {
      return $([document, document.body]).height(innerHeight);
    }), false);
    $('input[type="text"], input[type="search"]').on('blur', function() {
      return window.scrollTo(document.body.scrollLeft, 0);
    });
    return setTimeout((function() {
      window.scrollTo(0, 0);
      $([document, document.body]).height(innerHeight);
      return $dummy.height(40);
    }), 0);
  };

  document.write("<div class=\"startup\">\n    <div id=\"logo\">RRR</div>\n</div>");

  window.applicationCache.addEventListener('downloading', function() {
    timerId = setInterval((function() {
      return $option.toggleClass('btn-light');
    }), BLINK_INTERVAL);
    return $version.html(VERSION + ' (downloading new version...)');
  });

  window.applicationCache.addEventListener('cached', function() {
    clearInterval(timerId);
    if ($option.hasClass('btn-light')) {
      $option.removeClass('btn-light');
    }
    return $version.html(VERSION);
  });

  window.applicationCache.addEventListener('updateready', function() {
    clearInterval(timerId);
    if (!$option.hasClass('btn-light')) {
      $option.addClass('btn-light');
    }
    return $version.html(VERSION + ' (new version available)');
  });

  window.applicationCache.addEventListener('error', function() {
    clearInterval(timerId);
    if (!$option.hasClass('btn-light')) {
      $option.addClass('btn-light');
    }
    return $version.html(VERSION + ' (cache error)');
  });

  types = ['checking', 'noupdate', 'downloading', 'progress', 'cached', 'updateready', 'obsolete', 'error'];

  for (_i = 0, _len = types.length; _i < _len; _i++) {
    type = types[_i];
    window.applicationCache.addEventListener(type, function(event) {
      return console.log(event.type);
    });
  }

  app.initializeGoogleMaps();

  $version.html(VERSION);

  app.initializeDOM();

  if (/iPhone/.test(navigator.userAgent) && /Safari/.test(navigator.userAgent)) {
    fullScreen();
  }

  window.onpagehide = function() {
    app.saveMapStatus();
    return app.saveOtherStatus();
  };

  setTimeout((function() {
    return $('.startup').on('webkitTransitionEnd', function() {
      return $('.startup').css('display', 'none');
    }).css('opacity', '0');
  }), STARTUP_TIME);

}).call(this);
