// Generated by CoffeeScript 1.6.1
(function() {
  var STARTUP_TIME, VERSION, fullScreen, type, types, _i, _len;

  VERSION = '(C) 2013 ICHIKAWA, Yuji (New 3 Rs)<br>Maps ver. 2.0.0';

  STARTUP_TIME = 2000;

  fullScreen = function() {
    var $body, $dummy;
    $body = $(document.body);
    $dummy = $("<div id=\"dummy\" style=\"position: absolute; width: 100%; height: " + screen.availHeight + "px; top: 0px\"></div>");
    $body.append($dummy);
    window.addEventListener('orientationchange', (function() {
      return $([document, document.body]).height(innerHeight);
    }), false);
    $('input[type="text"], input[type="search"]').on('blur', function() {
      return window.scrollTo(document.body.scrollLeft, 0);
    });
    return setTimeout((function() {
      window.scrollTo(0, 0);
      $([document, document.body]).height(innerHeight);
      return $dummy.remove();
    }), 0);
  };

  document.write("<div class=\"startup\">\n    <div id=\"logo\">RRR</div>\n</div>");

  types = ['checking', 'noupdate', 'downloading', 'progress', 'cached', 'updateready', 'obsolete', 'error'];

  for (_i = 0, _len = types.length; _i < _len; _i++) {
    type = types[_i];
    applicationCache.addEventListener(type, function(event) {
      return console.log('cache', event.type);
    });
  }

  app.initialize();

  if (/iPhone/.test(navigator.userAgent) && /Safari/.test(navigator.userAgent)) {
    fullScreen();
  }

  window.onpagehide = app.saveMapStatus;

  if (/WebKit/.test(navigator.userAgent)) {
    setTimeout((function() {
      return $('.startup').on('webkitTransitionEnd', function() {
        return $('.startup').css('display', 'none');
      }).css('opacity', '0');
    }), STARTUP_TIME);
  } else {
    $('.startup').css('display', 'none');
  }

}).call(this);
