// Generated by CoffeeScript 1.3.3
(function() {

  app.initializeGoogleMaps();

  app.initializeDOM();

  app.tracer.start();

  window.onpagehide = function() {
    app.tracer.stop();
    app.saveMapStatus();
    return app.saveOtherStatus();
  };

}).call(this);
