// Generated by CoffeeScript 1.3.3
(function() {
  var watchPosition;

  app.initializeGoogleMaps();

  app.initializeDOM();

  watchPosition = new app.WatchPosition().start();

  window.onpagehide = function() {
    watchPosition.stop();
    app.saveMapStatus();
    return app.saveOtherStatus();
  };

}).call(this);
